[[redirects]]
  from = "/feed/"
  to = "/feed/index.xml"

[[redirects]]
  from = "/onderwerpen/nieuwsbrief/feed/"
  to = "/onderwerpen/nieuwsbrief/feed.xml"

[[redirects]]
  from = "https://sinds82.nl/about"
  to = "https://reinierladan.nl/over"
